name: ai_photo_scavenger_hunt
description: "A fun photo scavenger hunt game implemented using Flutter and Google AI Dart SDK."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  image_picker: ^1.0.7
  scavenger_hunt_repository:
    path: packages/scavenger_hunt_repository

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
